name: Laravel CI

on:
  push:
    branches:
      - master

jobs:
  laravel_building:
    name: Laravel Building
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install dependencies
        run: composer install
      - name: Build Laravel
        run: php artisan build

  laravel_testing:
    name: Laravel Testing
    runs-on: ubuntu-latest
    needs: laravel_building
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install dependencies
        run: composer install
      - name: Run PHPUnit
        run: php artisan test

  notification:
    name: Notification
    runs-on: ubuntu-latest
    needs: [laravel_building, laravel_testing]
    steps:
      - name: Check job status
        run: |
          status_building=$(curl -s -u "username:token" -X GET https://api.github.com/repos/{owner}/{repo}/actions/jobs/job_id | jq -r '.conclusion')
          status_testing=$(curl -s -u "username:token" -X GET https://api.github.com/repos/{owner}/{repo}/actions/jobs/job_id | jq -r '.conclusion')
          if [[ $status_building == "success" && $status_testing == "success" ]]; then
            echo "Sukses"
          else
            echo "Gagal"
          fi
